version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
        - './:/var/www/html:delegated'
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    expose:
      - 3306
    volumes:
#      - db:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_PORT: 3306
    restart: always
    ports:
      - "8001:80"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
        - redis:/data

volumes:
  redis:
    driver: local
  db:
    driver: local


